name: Server deployment

on:
  push:
    branches: ['main']

env:
  DEPLOY_PATH: /root/bossflix
  PM2_NAME: woofsro

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps (CI)
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        env:
          GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
          TOR_PASSWORD: ${{ secrets.TOR_PASSWORD }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: build-folder
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: build-folder
          path: build

      - name: Remote prepare (clean target)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            mkdir -p "${{ env.DEPLOY_PATH }}"
            rm -rf "${{ env.DEPLOY_PATH }}"/*

      - name: Upload build to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: 'build/*'
          target: '${{ env.DEPLOY_PATH }}'
          overwrite: true
          strip_components: 1
      - name: PM2 restart
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            pm2 restart "${{ env.PM2_NAME }}"
            pm2 save
